### ISSUE TITLE
Bug: Extremely laggy JSG machines

### ISSUE THREAD

**Issue by Renno231** [Tau-ri-Dev/Mod-JSG-1.12.2#298]
**Describe the bug**
JSG machines cause extreme lag

**To Reproduce**
1. use JSG machine
2. leave JSG machine placed in world

**Expected behavior**
Machines shouldn't be causing extreme lag

**Screenshots**
![2023-11-12_18 01 05](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/75190549/a0e2a3bc-5ea4-4d38-b172-ab3b3b0a0622)
![2023-11-12_18 02 20](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/75190549/ad75096a-c474-4595-9e84-dfa0f9e6853f)
![2023-11-12_17 10 54](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/75190549/bd914fe5-606f-4658-8a34-514e398c7a14)
![2023-11-12_18 02 21](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/75190549/429fa868-4b2b-4ee7-bd5e-b2471fc2cca9)

**Mod version**
4.11.2.2

**Additional context**

**My whole JSG config (as .zip)**
This is on a server, I don't have the server configs.

**Comment by VirgilCore** [comment]
attached is the server's configs.
[zpconfig.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13342838/zpconfig.zip)

**Comment by MineDragonCZ** [comment]
Anyway, thanks for reporting :)
