### ISSUE TITLE
Suggestion: Fabric Port

### ISSUE THREAD

**Issue by LokeYourC3PH** [Tau-ri-Dev/Mod-JSG-1.12.2#315]
**Describe the suggestion**
I am hoping there is a time and way for this mod to be ported to Fabric 1.20.1 as well as that is all we need to complete our server :)
Thanks~

**Comment by Fredyman95** [comment]
Try to ask on discord :D

**Comment by MineDragonCZ** [comment]
> **Describe the suggestion** I am hoping there is a time and way for this mod to be ported to Fabric 1.20.1 as well as that is all we need to complete our server :) Thanks~

I'm sorry, but we are not planning to port the mod to **fabric**.

**Comment by LokeYourC3PH** [comment]
Tragic, but somewhat expected. Thanks anyways.
