### ISSUE TITLE
Bug: AC tries to register dim that is not registered

### ISSUE THREAD

**Issue by TheDarkWilliams** [Tau-ri-Dev/Mod-JSG-1.12.2#318]
**Describe the bug**
i had The Space Age mod, it teleported me to "earth orbit" i came back down and a large number of stargates had spawned and crashed minecraft, i had to uninstall the Stargate mod to go back into the world without it crashing. ever since then after reinstalling the stargate mod when i go into another dimension it crashes the game and says 'dimension doesn't exist', i uninstall the stargate mod again and it goes back to normal. i have also removed The Space age mod as well. it has also effected The nether, i can't use the nether portal.

**Mod version**
jsg-1.12.2-4.11.2.6-client

[jsg.zip](https://github.com/Tau-ri-Dev/Mod-JSG-1.12.2/files/13755326/jsg.zip)

**Comment by MineDragonCZ** [comment]
Nether portals and End portals are disabled by JSG by default.
About the issue, I can't fix anything that I don't have log to...

**Comment by TheDarkWilliams** [comment]
i have just tried doing the same thing to get the issue to occur and it has happened, this is the crash code that minecraft gives me
it happens when i use the admin gate device in any other dimension.
'The game crashed whilst rendering screen
Error: java.lang.IllegalArgumentException: Could not get provider type for dimension 3, does not exist'


here's the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TenshiCore (TenshiLib-1.12.2-1.2.3.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.34.1_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 12/22/23 6:50 PM
Description: Rendering screen

java.lang.IllegalArgumentException: Could not get provider type for dimension 3, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:164)
	at tauri.dev.jsg.gui.admincontroller.AddressesSection.renderFg(AddressesSection.java:341)
	at tauri.dev.jsg.gui.admincontroller.GuiAdminController.drawForeground(GuiAdminController.java:212)
	at tauri.dev.jsg.gui.JSGTexturedGui.func_73863_a(JSGTexturedGui.java:56)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1462)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:164)
	at tauri.dev.jsg.gui.admincontroller.AddressesSection.renderFg(AddressesSection.java:341)
	at tauri.dev.jsg.gui.admincontroller.GuiAdminController.drawForeground(GuiAdminController.java:212)
	at tauri.dev.jsg.gui.JSGTexturedGui.func_73863_a(JSGTexturedGui.java:56)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)

-- Screen render details --
Details:
	Screen name: tauri.dev.jsg.gui.admincontroller.GuiAdminController
	Mouse location: Scaled: (115, 207). Absolute: (575, 319)
	Screen size: Scaled: (512, 271). Absolute: (2560, 1351). Scale factor of 5

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheDarkWilliams'/522, l='MpServer', x=-4092.78, y=30.00, z=-4313.93]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 21264251 game time, 1373354 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['TheDarkWilliams'/522, l='MpServer', x=-4092.78, y=30.00, z=-4313.93]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3180241152 bytes (3032 MB) / 5939134464 bytes (5664 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 14
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version               | Source                                   | Signature                                |
	|:------ |:------------------ |:--------------------- |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2                | minecraft.jar                            | None                                     |
	| LCHIJA | mcp                | 9.42                  | minecraft.jar                            | None                                     |
	| LCHIJA | FML                | 8.0.99.99             | forge-1.12.2-14.23.5.2860.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2860          | forge-1.12.2-14.23.5.2860.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaeroworldmap_core | 1.12.2-1.0            | minecraft.jar                            | None                                     |
	| LCHIJA | opencomputers|core | 1.8.3                 | minecraft.jar                            | None                                     |
	| LCHIJA | architecturecraft  | @VERSION@             | architecturecraft-1.12-3.108.jar         | None                                     |
	| LCHIJA | bookshelf          | 2.3.590               | Bookshelf-1.12.2-2.3.590.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ptrmodellib        | 1.0.5                 | PTRLib-1.0.5.jar                         | None                                     |
	| LCHIJA | props              | 2.6.3.7               | Decocraft-2.6.3.7_1.12.2.jar             | None                                     |
	| LCHIJA | llibrary           | 1.7.20                | llibrary-1.7.20-1.12.2.jar               | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil             | 8.0.5                 | fossilsarcheology-8.0.6.jar              | None                                     |
	| LCHIJA | hardcoredarkness   | 2.0                   | HardcoreDarkness-MC1.12.2-2.0.jar        | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | opencomputers      | 1.8.3                 | OpenComputers-MC1.12.2-1.8.3+274990f.jar | None                                     |
	| LCHIJA | jsg                | 1.12.2-4.11.2.6       | jsg-1.12.2-4.11.2.6-client.jar           | None                                     |
	| LCHIJA | malisiscore        | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar             | None                                     |
	| LCHIJA | malisisdoors       | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar            | None                                     |
	| LCHIJA | malisisswitches    | 1.12.2-5.1.0          | malisisswitches-1.12.2-5.1.0.jar         | None                                     |
	| LCHIJA | redstonepaste      | 1.7.5                 | redstonepaste-mc1.12-1.7.5.jar           | None                                     |
	| LCHIJA | shutters           | 1.12.2-1.0-pre        | shutters-1.12.2-1.0.jar                  | None                                     |
	| LCHIJA | tenshilib          | 1.2.3                 | TenshiLib-1.12.2-1.2.3.jar               | None                                     |
	| LCHIJA | thedalekmod        | (Update 64.1.0)       | thedalekmod-64.1.0.jar                   | None                                     |
	| LCHIJA | worldedit          | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar | None                                     |
	| LCHIJA | xaeroworldmap      | 1.34.1                | XaerosWorldMap_1.34.1_Forge_1.12.jar     | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TenshiCore (TenshiLib-1.12.2-1.2.3.jar)
  com.flemmli97.tenshilib.asm.ASMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
  li.cil.oc.common.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.34.1_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.EntityPlayerMPTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
  xaero.map.core.transformer.MinecraftServerTransformer
  xaero.map.core.transformer.MinecraftTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 537.70' Renderer: 'NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.70, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Thedarkwilliams TARDIS Texture pack
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 11
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 537.70
	OpenGlRenderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by TheDarkWilliams** [comment]
hi,

i did more testing this morning and it appears to only crash when using the Stargate Admin Device, as i visited all the places it had crashed previously and it hasn't crashed yet. so, so far there's a simple solution: im not going to use the Stargate Admin Device.

thank you for your help!

**Comment by matesaman9910** [comment]
Close the issue if you want 🙃

**Comment by MineDragonCZ** [comment]
> hi,
> 
> i did more testing this morning and it appears to only crash when using the Stargate Admin Device, as i visited all the places it had crashed previously and it hasn't crashed yet. so, so far there's a simple solution: im not going to use the Stargate Admin Device.
> 
> thank you for your help!

Not using an AC Is not a solution xd We need to fix the issue
