### ISSUE TITLE
Bug: GDO doesn't open Iris on Code Input

### ISSUE THREAD

**Issue by TheRedCreations** [Tau-ri-Dev/Mod-JSG-1.12.2#322]
**Describe the bug**
Opening Iris via GDO to Computer

**To Reproduce**
https://youtu.be/im5g0QVuEAA

**Expected behavior**
Open Iris with the Code Tab on GDO

**Mod version**
4.11.2.6 (latest)

**My whole JSG config (as .zip)**
default config

**Comment by MineDragonCZ** [comment]
AGS bug due to change in JSG code
