### ISSUE TITLE
Bug: SERVER CRASHES

### ISSUE THREAD

**Issue by matesaman9910** [Tau-ri-Dev/Mod-JSG-1.12.2#323]
When trying to start an aternos server it crashes

1. Go to this link [https://mclo.gs/URDsZu8](url)
2. Click on Line #844
3. See error

Expected behavior
Server starts

![image](https://github.com/Tau-ri-Dev/Mod-JSG-1.12.2/assets/100013611/9a212cc3-8fdd-4ac0-9e8a-2bcbe87b65af)
![image](https://github.com/Tau-ri-Dev/Mod-JSG-1.12.2/assets/100013611/6a774bc2-9d13-49ab-9cf3-cebfee3a499c)

**Mod version**
[jsg-1.20.1-5.0.0.1-Alpha.jar](https://aternos.org/files/mods#)

Thanks for fixing the issue in the next update if possible!

**Comment by matesaman9910** [comment]
Here:
https://aternos.org/files/crash-reports/crash-2024-02-06_15.19.54-fml.txt

**Comment by matesaman9910** [comment]
> the url is invalid. Please send the whole crash report

Here:
https://aternos.org/files/crash-reports/crash-2024-02-06_15.19.54-fml.txt
Or here:
https://mclo.gs/jBbtQTX

**Comment by YETIMAN2020** [comment]
mine also crashes 1.20.1 i realize it could also be because im running all the mods 9 but it launches fine on client so im not sure here is the log 
https://mcpaste.io/bf8f1f4985d10598

**Comment by MineDragonCZ** [comment]
Fixed
