### ISSUE TITLE
Bug: Abydos has no floor blocks that are not sand

### ISSUE THREAD

**Issue by IronmanVeronika** [Tau-ri-Dev/Mod-JSG-1.12.2#327]
the abydos world is only sand. This is bad because if you dig down you fall into the void and the world falls in too 

pls add a ground layer of solid blocks

**Screenshots**

version 1.20.1 5.0.2.0 beta

**Comment by MineDragonCZ** [comment]
Wrong repo... Use https://justsgmod.eu/issues to get there...

But yeah, we will
