### ISSUE TITLE
Bug: Searching not working as intended after I scrolled past 1st entry | Admin Controller

### ISSUE THREAD

**Issue by Nexusatko** [Tau-ri-Dev/Mod-JSG-1.12.2#329]
**Describe the bug**
If you try to search after you scroll the 1st entry in the Admin Controller, any search attempt will come up as empty result.
**To Reproduce**
1. Open Admin Controller and scroll enough to have 1st entry disappear out of showing view
2. Try search anything or any parameters in the search box next to Toggle iris.
3. You end up with blank search result even if search term was correct. :)
* PS: If you start inputting letters into search box, it may come up with some matched entries to that letter, but it seems that it's limited in range. So actually, if I were to search something that may be next to desired search term, it may or may not come up. It seems random at this point what can be searched after scrolling past 1st entry.

**Expected behavior**
Search whenever and whatever is in the gate network instead of shuffled behaviour..

**Mod version**
jsg-1.12.2-4.11.2.6-client.jar and same version on server.

**Config or additional context is not applicable in this case.**

**Comment by MineDragonCZ** [comment]
Fixed
