### ISSUE TITLE
Bug: Notebook opening crashes the game

### ISSUE THREAD

**Issue by Deimos1054** [Tau-ri-Dev/Mod-JSG-1.12.2#336]
**Describe the bug**
I am not completly sure how it happens, all I know is that the game crashes when I try to open the Notebook (2 pages), a single page works fine, am on my server... The universe Dialer seems to work fine... gave it 2 addresses and it didnt crash...

**To Reproduce**
Not sure... heres the mod list from Google Drive
https://drive.google.com/drive/folders/1YBaK_U2gDycxHDBCrcHGVu8ZQrJZ4rGO?usp=sharing

**Expected behavior**
When opening the edit thing on the Notebook, the game crashes

**Screenshots**
I dont have any Screenshots... nor do I know what type needs to be put here...

**Mod version**
JSG version is 4.11.2.6

**Additional context**
If you'd want to test if it crashes you too (to see if it can be fixed, like, if your a mod dev, just ping me on the DC server for JSG, the names Origin...

**My whole JSG config (as .zip)**
Am gonna put mine and the servers Config here
[jsg (Client).zip](https://github.com/user-attachments/files/15856186/jsg.Client.zip)

[jsg (Server).zip](https://github.com/user-attachments/files/15856188/jsg.Server.zip)

**Crashlog**:
[crash-2024-06-16_06.13.40-client.txt](https://github.com/user-attachments/files/15856196/crash-2024-06-16_06.13.40-client.txt)

**Comment by Fredyman95** [comment]
I know where is issue. Its fixed in dev version of mod. Basicly little bit stupid… you name your single page address e.g END city portal gate

But notebook page can use only limit number of characters - so END city porta


And when you press INSERT game will crash because limit for name of address is longer then is allowed

**Comment by Deimos1054** [comment]
k... anyway, heres the video...

[Uploading Minecraft 1.12.2 w_Just Stargate Mod 4.11.2.6 2024-06-16 07-32-26.zip…]()

**Comment by Deimos1054** [comment]
hope it gets updated soon... I remember that, in the older versions, this was, actually not a problem...

**Comment by Fredyman95** [comment]
> hope it gets updated soon... I remember that, in the older versions, this was, actually not a problem...

Well its because we edit tons of things inside JSG that allows us to do new stuffs as generate gate with suspicious pages (previous version doesn't have those pages... :/ ) and sometimes these things happends...

**Comment by MineDragonCZ** [comment]
Ok, from what i can say, it should be minecraft problem that i don't have much capability to fix... So sorry
