### ISSUE TITLE
Bug: Calling stargate's engageSymbol function causes internal errors

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [Tau-ri-Dev/Mod-JSG-1.12.2#338]
**Describe the bug**
When using the latest releases of OpenComputers and JSG for 1.12.2, calling stargate.engageSymbol seems to randomly cause an internal error.

**To Reproduce**
1. Build Milky Way Stargate and connect computer to it
2. Call engageSymbol function repeatedly until...
3. Computer halts due to internal error

**Expected behavior**
Attempting to dial any symbols on a functioning idle gate should not cause internal errors.

**Mod version**
jsg-1.12.2-4.11.2.6-client
OpenComputers-MC1.12.2-1.8.5+179e1c3

**Comment by TinyDeskEngineer06** [comment]
I tried using a dialer program that used symbol indices instead of names in the engageSymbol calls, and so far it's successfully engaged 5 symbols without any errors, so it looks like it only happens with symbol names.

**Comment by Fredyman95** [comment]
What is the actual issue?
![image](https://github.com/user-attachments/assets/24a1f6b0-6c21-4495-855e-696004497491)

I tried even simple dialing script with for loop and no internal error - I tried that 7 times...

**Comment by TinyDeskEngineer06** [comment]
I have no clue, it happens inconsistently, the Java stack trace logged at the time of the error doesn't point to JSG, but the error never seems to happen with regular OpenComputers functions.

**Comment by TinyDeskEngineer06** [comment]
...Aaand I wasn't able to reproduce the bug after trying again. Both in OpenOS's Lua interpreter and in a program.

I wonder what's different this time. I restarted Minecraft several times last try and errors kept occurring, but now they aren't occurring at all.

**Comment by RosalindMaximoff** [comment]
Hello 👋  um can I ask you something  that happens most of that I try.i can't make the connection with stargate and OpenComputers. 1 I installed the OpenOs. And then the code : pastebin run pAqHB264. Mut seems there's a problem it won't make the connection it says wget/ something  lua 72 sunguard and ect.  I try every possible ways but at the end same error  or there's a different code or something else  if it cannot be make the connection can you suggest otger mods competitive with just jsg 1.12.2

**Comment by Fredyman95** [comment]
> b

This is not bug related to JSG or AGS - you are using outdated JAVA or it is bug of OC mod - solution for this issues you can find out on our discord... Also command `pastebin run pAqHB264` is outdated - on our discord you can find out new command for updated version for new installer of AGS

**Comment by Fredyman95** [comment]
> Hello 👋 um can I ask you something that happens most of that I try.i can't make the connection with stargate and OpenComputers. 1 I installed the OpenOs. And then the code : pastebin run pAqHB264. Mut seems there's a problem it won't make the connection it says wget/ something lua 72 sunguard and ect. I try every possible ways but at the end same error or there's a different code or something else if it cannot be make the connection can you suggest otger mods competitive with just jsg 1.12.2

This is not issue of JSG or AGS - this can be bug of OC mod or you are using  outdated version of JAVA. Solution for this issue you can find out on our discord server... Also command `pastebin run pAqHB264` is outdated - this version of AGS doesnt support new mechanics of JSG... New installers command you can find out also on our discord.

**Comment by RosalindMaximoff** [comment]
Thank you for help 🤝I  didn't know that I'm not using much discord ( only for updates ) and if you can help me exactly where I can find these things you sad I would be appreciate 😢 sorry if I ask much

**Comment by Fredyman95** [comment]
> Thank you for help 🤝I didn't know that I'm not using much discord ( only for updates ) and if you can help me exactly where I can find these things you sad I would be appreciate 😢 sorry if I ask much

Instructions arent easy - like 3 steps to solve it...
I can send you here discord invite - https://discord.com/invite/NXp4NA8mBR
and
new command for AGS - `pastebin run X0QSjYkm`

**Comment by RosalindMaximoff** [comment]
Yep I saw some solutions but I'm not using Curseforge minecraft logging I'm using TLauncher and I try new code : Pastebin run X0QSjYkm but anyway I don't want to bother you for my problems have a nice Night ( in my country and your I guess Ihave a nice Day sir 👋🫂

**Comment by Fredyman95** [comment]
> Yep I saw some solutions but I'm not using Curseforge minecraft logging I'm using TLauncher and I try new code : Pastebin run X0QSjYkm but anyway I don't want to bother you for my problems have a nice Night ( in my country and your I guess Ihave a nice Day sir 👋🫂

Problem is still that you are using outdated java - you need to updated. No later if you using CF, vanilka launcher or Tlauncher…

regards Fredy

**Comment by RosalindMaximoff** [comment]
I downloaded the windows offline 64 bits but when it reach the end it says
outdated and regrets to install it. Is this the main problem ?  I gues I
have to try it but I don't have any hope that it will work. OK anyway
thanks for your help I will try it and if it works I will send you message

На чт, 1.08.2024 г., 10:15 ч. Fredyman95 ***@***.***> написа:
