### ISSUE TITLE
[1.12.2] Strange RAM consumption

### ISSUE THREAD

**Issue by AlexCheviesGC** [Tau-ri-Dev/Mod-JSG-1.12.2#343]
**Describe the bug**
I have 16GB installed in my PC and when the game is allocated 8GB when playing with this mod it almost always crashes with an error of insufficient RAM. When I allocate 4GB of RAM for the game, the game works but obviously due to the smaller amount of allocated RAM the performance decreases. I use quite a few optimization mods and special JVM arguments. Perhaps this may have something to do with the problem. I would be glad to receive help or recommendations on those optimization mods that are better not to install or, on the contrary, will help.

**To Reproduce**
1. Install JSG
2. Allocate 8GB of RAM to the game (if the system has 16GB)
3. Try to... Run a game?
4. Allocate 4Gb of RAM
5. Just play with reduced performance at draw distance... More than 4 chunks?

**Expected behavior**
Just... Normal game experience without any performance degradation with sufficient allocated RAM? Well, that is, without a JSG, I can easily allocate 8GB of RAM and play with excellent performance.

**Mod version**
jsg-1.12.2-4.11.2.7

**Additional context**
My PC is equipped with i5-6500, GTX 1050Ti and 16GB DDR4 in dual channel. I also completely disabled the swap file in Windows and use these arguments for the JVM: `-Xms8G -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UseCompressedOops -XX:-UsePerfData`

**My whole JSG config**
Just default without any changes.

**Comment by Fredyman95** [comment]
Try to turn off all mods all optimalization mods - and later try to turn it one by one.

also note that some of these mods (e.g better FPS) need right setting for right performace on your computer. Othervise even without JSG these mods can make your game experience worse - JSG can make it only more obvious.

**Comment by AlexCheviesGC** [comment]
> Try to turn off all mods all optimalization mods - and later try to turn it one by one.
> 
> also note that some of these mods (e.g better FPS) need right setting for right performace on your computer. Othervise even without JSG these mods can make your game experience worse - JSG can make it only more obvious.

I tried running the game with only JSG and the situation is the same.

[latest.log](https://gist.github.com/AlexCheviesGC/6b84842dc95495e2ebe1869b9019c775)

**Comment by Fredyman95** [comment]
https://knowledge.informatica.com/s/article/629910?language=en_US
