### ISSUE TITLE
How do you dial between groups?

### ISSUE THREAD

**Issue by DarianLStephens** [Tau-ri-Dev/Mod-JSG-1.12.2#344]
I have been struggling with this for a few days, now, and I haven't been able to figure this out.
I want to dial from an upgraded Milky Way gate + DHD (Stole the DHD upgrade from the Nether gate) to the Universe gate in the End, but I have absolutely no idea how. There doesn't seem to be any information about this anywhere, not on the wiki nor in any other issues here that I've seen.
Holding the page doesn't highlight anything on the DHD, and I don't know how or if you can translate between them manually.

Do I need to somehow find a pre-existing Universe gate in the Overworld and steal it, and hope it has dialer thing? I can't make the dialer because I need Trinium to make the PCB maker and crystal chamber, and as far as I can tell, that's _only_ available as an ore from the End.
Maybe I could make a dialing program with OC that can make the gate dial anyway?

I want to know what options I have, because I haven't been able to find them anywhere. All the wiki says is 'you need 9 symbols to dial between addresses', which is all well and good, but I don't know how to dial these different-symbol addresses to begin with.

**Comment by ThatSteveThing** [comment]
So what you need is a Milky way Glyph crystal and the Glyph crystal that shows the full 9 symbol address, to be put into a Universe gate, which will allow you to see the Milky Way address for that gate.

Same thing goes if you wanted to try dialing a Pegasus gate from a Milky way gate. You would need to put a Milky Way Glyph crystal into the Pegasus gate, alongside the upgrade crystal that lets you get the full address, and then once you have that address, give it a dial.

**Comment by ThatSteveThing** [comment]
Also as well, I haven't played the latest update(s) for 1.20, but I'm pretty sure that similar to 1.12, you can't find Universe gates in the Overworld, they only spawn in the End dimension, so you wouldn't be able to find one and steal the dialer from it.

Plus, to get a Universe dialer, you have a chance to find them in the Tokra structures that spawn or even in ancient totems (unless those loot tables have been changed). The only other way to get one would be to get a piece of the paper and put it into the slot in a Universe gate where you would normally get the address, and it'll turn it into a Universe dialer.
