### ISSUE TITLE
:Bug ERROR CODE LOADING

### ISSUE THREAD

**Issue by NX01AURORA** [Tau-ri-Dev/Mod-JSG-1.12.2#346]
Bug: ZDRAVÍM MAM TADY JEDEN PROBLEM SE PŘIPOJIT NA SECRET OF AVALON PŘÍ NAČITNÍ SPUŠŤENÍ HRY JSEM SEPŘI  PŘÍPOJENÍM MÁM CHYBU A ŘEKLOMITO AŤ TO POŠLU PŘES TVURCE MAM TADY CHYBA CODE A NEVÍM JESTLI TO MÁM POSLAT NA DISCORD NEBO NĚKAM JINAM? 
![Snímek obrazovky 2024-09-30 152615](https://github.com/user-attachments/assets/573f7f91-ed1e-4eab-b621-e21d273f562d)

**Comment by Fredyman95** [comment]
Did you check crash log? I bet its not enough allocated RAM…

**Comment by NX01AURORA** [comment]
HELLO I NEED AGAIN HELP I CEN´T JOIN SERVER SECRET OF AVALON GAME ON WHITELIST WERE FOUND DISCORD OR OFFICIAL WEBSIDE JSG STARGATE MOD
